require("jsonlite")
require("RCurl")
Austin_SALARIES_df <- data.frame(fromJSON(getURL(URLencode('oraclerest.cs.utexas.edu:5001/rest/native/?query="select * from AUSTIN_SALARIES"'),httpheader=c(DB='jdbc:oracle:thin:@aevum.cs.utexas.edu:1521/f16pdb', USER='cs329e_rsb2273', PASS='orcl_rsb2273', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON'), verbose = TRUE) ))
#summary(df)
summary(Austin_SALARIES_df)
head(subset(Austin_SALARIES_df, DEPARTMENT_NAME == "Fire" & ANNUAL_SALARY > 10000))